"use strict";
function generaNumero(Min,Max){

    let n = Math.floor((Max-Min+1)*Math.random())+Min;
    /*formula per generare un numero tra mix e max estremi inclusi*/
    return n;
}
///per responsive ricaricare la pagina
let testi = ["Questa è stata un ottima run, soprattutto per il fatto che Sansone non è un personaggio che uso di frecuente. Infatti egli comincia con un oggetto chiamato blode lad(ogni volta che si viene colpiti aumenta danno proporzionalmente) , considero questo oggetto molto utile poichè del danno in più gratis non è da poco.<br>La run continua in modo molto produttivo con un oggetto attivo chiamato prayer card (ogni volta attivato regala un mezzo cuore bianco i cuoli quando si uniscono ad un altro cuore bianco ne creano uno rosso. Affrontando il primo boss trovai woodden spoon (+0.30 di velocità) che con la velocità che si ritrova sampson è molto utili. Nel secondo piano non ho avuto molti sobbalzi fatta eccezione per l'oggetto nella stanza del tesoro ovvero stigmata (un cuore in più e +0.58 di danno) e un patto con il diavolo che mi ha fruttato 3 cuori blu. Concludendo il piano trovando le scarpe di mamma (+5.25 di gittata) decido di andare oltre quindi passare al piano successivo. Il piano sottostante al precedente non ha regalato molte gioe poichè i 2 oggetti trovati non erano granchè:mom's Eyeshadow (una volta ogni tanto un nemico accacca con te, fatta eccezione per i boss) e ball of bandage (gira intorno a te una palla di bendaggi che fa danno ai nemici), però dopo il boss scorgendo la percentuale di fede molto alta entro nella stanza del patto angelico e li ho trovato uno degli oggetti più forti del gioco :  Wafer (fa in modo di ,a run inoltrata, subire mezzo cuore invece di un cuore alla volta), soddisfatto e con l'angelo sconfitto e quindi preso un pezzo di chiave (una chiave che intera fa in modo di poter incontrare mega satana nella dark room) decido di andare nella stanza del sacrificio e sperare di trovare un oggetto decente (cosa che accade in parte poichè l'oggetto trovato aumenta solo la percentuale di patto angelico).",
"Questa , come al solito, è stata una run fallimentare per molteplici motivi, il più importante dei quali è che io non sono bravo ad utilizzare questo personaggio anche se paradossalmente è uno dei miei personaggio preferiti.La run comincia con un oggetto che personalmente cosindeso inutile cioè Holy Water (Quando si prende danno rilascia del liquido, questo fa danno ad i nemici). Sconfiggendo il boss entro in possesso di mr.Dolly (+3 cuori a caso, +5.25 gittata, +5 volocità di sparo) e mi precipito al piano successivo.Il secondo piano mi impone una scelta molto difficile cioè prendere o no controlled tears (con un personaggio una tipo di attacco 'normale' e quindi anche The soul, fa in modo di non sparare più lacrime ma di controllarne a distanza una) il mio poblema era nel fatto di non sapere in che modo il mio The forgotten sarebbe andato ad attaccare e con mio  molto stupore semplicemente mi ha creato una lacrima da scagliare con il bastone.Dopo la mia vittoria del boss e quindi aver preso rotten meat (HP up) ho preso pentagram (+1.96 danno) e little brimstone (un minion che spara un raggio laser a caricamento) dopo di ciò sono volato al terzo piano.Un terzo piano ad essere sincero un pò statatico poiche presi little chad (una volta ogni tanto droppa un cuore) dal boss e sad onion (+4 volcità di sparo) dalla stanza del tesoro non ho avuto altre emozioni.Arrivato al piano successivo ho trovato subito guppy's tail(un item che oltre ad essere un peszzo di guppy fa in modo di farmi trovare più bauli dorati) e quindi ripresi unpò le speranze anche se con il piano precedente erano andate a scemare.Un piano che aimè è finito come pensavo in tragedia, trovando Gympi e quindi andando nel negozio ho incontrato un boss che ha segnato la mia fine.",
"Questa run è stata la run più fortunata che io abbia mai fatto in greed mode per via degli straodinari oggetti trovati.La run comincia con un semplice stem cells(HP  up) per poi comprare un raw liver(2HP up) e ricevere 8 inch nails(+2.36 di danno e trafonrmano le lacrime in chiodi, sono rari gli oggetti cn così tanto danno in più)Il secondo piano comincia con 2 oggetti molto sgalfi cioè blood clot(La lacrima riceve un damage up di circa 0.50 e aummenta il range di entrambe di 1 circa) e bozo(+un cuore blu e 0.10 di damage), un pò amareggiato ma pieno di speranza sconfiggo il piano con molta facilità per poi andare a comprare woodden spoon(+0.30 di velocità) e cursed eye(lancia più chiodi alla volta).Pieno di orgoglio avendo scoperto la sinergia con cursed eye mi accingo ad andare al terzo piano, dove trovo un paio di oggetti buonissimi quali:magic mushroom(alza tutte le statistiche) , magic scab(Hp up e più 1 a fortuna) e angel prism(forse l'oggetto più forte del gioco, esso quando una lacrima ,o nel mio caso un chiodo, lo attraversa moltiplica la lacrima, esso conta come minion), infine decido di concludere il piano comprando una batteria che tiene energia.Fiero della mia onnipotenza vado al piano successivo in cui nelle stanze degli oggetti trovo di utile solo breakfast(Hp up), dopo poco decido di comprare più oggetti scontati possibili quali mini mush(+0.30 speed ma -4.25 range) e the belt (+0.30 di velocità ma per un massimo di 2 quindi solo 0.10).Dopo un patto con i diavolo molto povero decido di continuare a comprare degli oggetti scontati tipo:Odd mushroo(Fire rate up) per diventare fun guy (una delle tante trasformazioni del gioco arrivataci grazie agli oggetti di tipo fungo),torn photo(+0.16 fire rate) , meat!(+0.53 di danno e HP up) e tooth picks(+0.16 fire rate e +0.20 velocità lacrime).Nel stanza del patto angelico ho deciso di prendere jesus juice(+0.81 danno e +0.25 gittata), dopo di ciò ho optato per  comprare bffs(fa diventare i minion più forti) e andare a prendere gli oggetti in 'regalo' cioè mom's eye(teoricamente fa in modo di sparare anche dalla nuca ma non sinergizzava quindi era inutile) e safety pin(più cattiveria, +5.28 range e 0.16 velocità di sparo)Nel pen'ultimo piano (the shop) con il patto angelico trovo il santo gral(possibilità di volta e HP up) , nello shop invece compro una batteria che mi ricarica l'attivo e due oggetti scontati quali a snack (Hp up) e Binki(+un cuore azzurro).Nella stanza precedente all'ultimo boss ho trovato un oggetto che per il mio obbiettivo (raggiungere le 500 monete nella macchinetta delle donazioni per sbloccare la modalità greedier) è oro colato cioè 25 penny(da 25 monete).La run si coclude distruggendo uno dei boss più forti del gioco.",
"Isacc è il persoggio con cui ho più affinità anche perchè l'ho usato moltissimo.Cominciando male con un curse of the darkness trovo la small rock(+1.69 danno) , little monstro(minion che spara con il boss monstro) e placenta(ogni tanto rigenera mezo cuore e HP up).Scppando dalla maledizione vado al secondo piano che mi risultarà medio basso per una run in normal trovando Capricorn(alza tutte le statistiche) e tooth picks(+0.16 fire rate e +0.20 velocità lacrime).Il terzo piano non riserva sorprese molto gradite poichè shard of glass(quando prendo danno lascio una scia di rangue che fa danno ad i nemici) e magic scab(Hp up e più 1 a fortuna) non sono dei migliori che potessi trovare, però il patto con il diavolo sana la mia voglia di oggetti rari poichè prendendo un altare dei sacrifici riesco a trovare spirit of the night(mi fa diventare un fantasma).L'ultimo piano che si vede in questo video è il quarto, che oltre a due oggetti molto poco utili: soy milk(spara tante lacrime alla volta ma con poco danno) e sad onion(tears up) non regala soddisfazioni."];
window.onload=function () {
    cambiavideo(1)
}
function cambiavideo(c){
    let _p=document.getElementById("testovideo");
    let _video=document.getElementById("video")
    _video.src="isacc " + c + ".mp4";
    _p.innerHTML = testi[c-1];
}
